apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  selector:
    app: web-server
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
